# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbacf523cba369503ed037f4b6eed84c7f7eb25dde7d6021c0aab5e56b7b77d9636c9ad743e30b43ae9dfd6cf7e8864417b82657f2678245c23c1150b2eaffdd

test:
  secret_key_base: f1280aff5a9dcb7507c24dfbe6ac408e9751db4dc1919312f2e4a89e2310a4aab95f59a0560d0f25c487a9d55a31ad8699d2b71f45b5bc078dcdede0592b58f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
